name: Dependabot Automerge
on: pull_request
jobs:
  worker:
    runs-on: ubuntu-latest
    services:
      devnet:
        image: shardlabs/starknet-devnet:latest-seed0
        ports:
          - 5050:5050
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm --stream -r run build
      - run: pnpm test
      - run: xvfb-run --auto-servernum pnpm test:e2e
      - run: pnpm --cwd packages/dapp export
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |-
            await github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            await exec.exec("sleep 2")
            await github.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
