name: Run Tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  call-setup-workflow:
    uses: ./.github/workflows/setup.yml
  test:
    needs: call-setup-workflow
    runs-on: ubuntu-latest

    services:
      devnet:
        image: shardlabs/starknet-devnet:latest-seed0
        ports:
          - 5050:5050
    env:
      FILENAME: argent-extension-${{ github.ref_name }}

    steps:
      - name: "Download artifact"
        run: |
          OTHER_REPO="argentlabs/argent-x"
          WF_NAME="Run Tests"
          ARTIFACT_NAME="setup_dir.zip"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId --jq '.[0].databaseId'`
          echo ${RUN_ID}
          gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: unzip setup folder
        run: unzip -q setup_dir.zip
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .

      - name: Run tests
        run: yarn test

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run e2e tests
        run: xvfb-run --auto-servernum yarn test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            packages/extension/test-results/
            packages/extension/e2e/artifacts/playwright/
            packages/extension/e2e/artifacts/reports/
          retention-days: 5

      - name: Check bundlesize for chrome
        run: yarn run bundlewatch
      - name: Set filename prefix
        run: echo "FILENAME_PREFIX=$(echo ${{ env.FILENAME }}  | tr / -)" >> $GITHUB_ENV

      - name: Create chrome zip
        run: |
          cd packages/extension/dist
          zip -r ${{ env.FILENAME_PREFIX }}-chrome.zip ./*
          mv ${{ env.FILENAME_PREFIX }}-chrome.zip ../../../
          cd ../../../
      - name: Build Firefox version
        run: MANIFEST_VERSION=v2 yarn --cwd packages/extension build
      - name: Create firefox zip
        run: |
          cd packages/extension/dist
          zip -r ${{ env.FILENAME_PREFIX }}-firefox.zip ./*
          mv ${{ env.FILENAME_PREFIX }}-firefox.zip ../../../
          cd ../../../
      - name: Check bundlesize for firefox
        run: yarn run bundlewatch
      - name: Upload artifacts for firefox
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.FILENAME_PREFIX }}-firefox.zip
          path: "*-firefox.zip"
          retention-days: 5
      - name: Upload artifacts for chrome
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.FILENAME_PREFIX }}-chrome.zip
          path: "*-chrome.zip"
          retention-days: 5

      - name: Set GHA_BRANCH
        run: echo "GHA_BRANCH=$(echo $GITHUB_REF | awk -F / '{print $3}')" >> $GITHUB_ENV
      - name: comment PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPO: ${{ env.GHA_BRANCH }}
          INPUT_OWNER: ${{ github.repository_owner }}
        run: |
          gh pr comment ${{ env.GHA_BRANCH }} --body "[Builds for local testing](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
